package serverCode.managers;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;

/**
 * Class {@code PasswordManager} for keeping static methods for work this collection.
 * @author Ivan Nesterov
 * @version 1.3
 * @since 02.06.21
 */
public class PasswordManager {

    /**
     * Generates new password which contain latin letters and numbers
     * Password is generated by {@link java.security.SecureRandom}.
     * @return new password
     */
    public static String generateNewPassword() {
        String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
        SecureRandom random = new SecureRandom();
        StringBuilder password = new StringBuilder();
        for (int i = 0; i < 8; i++) password.append(chars.charAt(random.nextInt(chars.length())));
        System.out.println("Новый пароль сгенерирован.");
        return password.toString();
    }


    /**
     * Generated new hash for given string.
     * @param nudeString giving string
     * @param algorithm algorithm of hashing
     * @return hash string
     * @throws NoSuchAlgorithmException if algorithm is not exist
     */
    public static String getHash(String nudeString, String algorithm) throws NoSuchAlgorithmException {
        MessageDigest mDigest = MessageDigest.getInstance(algorithm);
        byte[] hash = mDigest.digest(nudeString.getBytes());
        StringBuilder strongPassword = new StringBuilder();
        for (byte b : hash) strongPassword.append(Integer.toString((b & 0xff) + 0x100, 16).substring(1));
        System.out.println("Hash string was received.");
        return strongPassword.toString();
    }
}